### Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/notice_db
#    username: root
#    password: root
#    initialization-mode: always
#
#
### Hibernate Properties
## The SQL dialect makes Hibernate generate better SQL for the chosen database
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl.auto: create
#      
#        dialect: org.hibernate.dialect.MySQLDialect
##        ddl-auto: create
##        show-sql: true
#          
## Hibernate ddl auto (create, create-drop, validate, update)
#   # hibernate:
#      
#
#
#
#logging:
#  level:
#    org.springframework: DEBUG